# Generated by Django 5.0.4 on 2024-04-27 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_code', models.IntegerField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_address', models.CharField(max_length=255)),
                ('customer_phone_number', models.CharField(max_length=13)),
                ('contact_person', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('goods_code', models.IntegerField(primary_key=True, serialize=False)),
                ('goods_type', models.CharField(max_length=9)),
                ('goods_name', models.CharField(max_length=255)),
                ('goods_manufacturer', models.CharField(max_length=255)),
                ('goods_warehouse_quantity', models.IntegerField()),
                ('goods_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('warehouse_number', models.IntegerField(primary_key=True, serialize=False)),
                ('warehouse_address', models.CharField(max_length=255)),
                ('warehouse_manager', models.CharField(max_length=255)),
                ('warehouse_phone_number', models.CharField(max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('sales_code', models.IntegerField(primary_key=True, serialize=False)),
                ('sales_date', models.IntegerField()),
                ('sales_cloth_quantity', models.IntegerField()),
                ('discount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('sales_customer_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_sales', to='database.customer')),
                ('sales_goods_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods_sales', to='database.goods')),
            ],
        ),
        migrations.AddField(
            model_name='goods',
            name='goods_warehouse_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.warehouse'),
        ),
    ]
