# Generated by Django 5.0.4 on 2024-04-28 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='sales_date',
            field=models.DateField(),
        ),
    ]
